'use client';


import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
    return (
        <div className={styles.container}>
            <Head>
                <title>QR app</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to Qr Labs
                </h1>


                <div className={styles.grid}>

                    <a href="/scan" className={styles.card}>
                        <h2>Scan a qr code&rarr;</h2>
                        <p>Scan a qr code with your camera</p>
                    </a>

                    <a href="/generate" className={styles.card}>
                        <h2> Generate a qr code&rarr;</h2>
                        <p> Generate a qr code with text or a link</p>
                    </a>

                </div>
            </main>


        </div>
    )
}
